on:
  push:
    tags:
      - 'v*'
name: Deploy Personnal Browser HomePage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        run: yarn build

      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/nicolas-choquet/www/browser-homepage
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}