on:
  push:
    tags:
      - 'v*'
name: Deploy Personnal Browser HomePage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependences
        run: yarn

      - name: Build app
        run: yarn build

      - name: Copy via ssh
#        uses: appleboy/ssh-action@v0.1.3
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/nicolas-choquet/www/browser-homepage
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIV_KEY }}
          passphrase: ${{ secrets.SSH_PRIV_KEY_PASSPHRASE }}
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.PASSWORD }}
#          key: ${{ secrets.SSH_PRIV_KEY }}
#          source: "dist/*"
#          target: /home/nicolas-choquet/www/browser-homepage