on:
  push:
    tags:
      - 'v*'
name: Deploy Personnal Browser HomePage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependences
        run: yarn

      - name: Build app
        run: yarn build

      - name: Copy via ssh
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIV_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          source: dist/*
          target: /home/nicolas-choquet/www/browser-homepage