on:
  push:
    tags:
      - 'v*'

name: Deploy Personnal Browser HomePage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependences
        run: yarn

      - name: Get remote env file
        run: wget ${{ secrets.ENV_FILE_URL }} .env

      - name: Build app
        run: yarn build

      - name: Install ssh
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/nicolas-choquet/www/browser-homepage
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIV_KEY }}
          passphrase: ${{ secrets.SSH_PRIV_KEY_PASSPHRASE }}